#!/usr/bin/env node

var path = require("path");
var spawn = require('child_process').spawn;
var pkgInfo = require(path.resolve(__dirname, '..', 'package.json'));

var target = path.join(process.env.TMPDIR || process.env.TEMP || '/tmp', pkgInfo.name + "-build");

var theArgs = process.argv.slice(2);
if (theArgs.length < 1) {
  theArgs = ['-r', '.'];
}

// Linux
var cmd = path.join(target, pkgInfo.productName, pkgInfo.name);

if (process.platform === 'darwin') {
  cmd = path.join(target, pkgInfo.productName + '.app', 'Contents', 'MacOS', pkgInfo.productName);
}

if (process.platform === 'win32') {
  cmd = path.join(target, pkgInfo.productName, pkgInfo.productName + '.exe');
}

// Spawn the application and hook-up stdout and stderr to see log messages
var toRun = cmd + " " + theArgs.join(" ");
console.log("running: " + toRun);

var child = spawn(cmd, theArgs);

child.stdout.on("data", function (data) {
  process.stdout.write(data);
});

child.stderr.on("data", function (data) {
  process.stderr.write(data);
});

child.on("exit", function(code) {
  console.log("exited with code: " + code);
});
